
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://nadia-metoui.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /nadia-metoui.github.io

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: " Nadia Metoui "
title: "  { Nadia Metoui } "
description: "Blog and website of Nadia Metoui PhD Student in Information Security & Trust."
keywords: "Nadia Metoui, Information Security & Trust, Access Control, Privacy, Risk Managment, Trust Management,  Anonymization"
favicon: "/img/green-safe.ico"

################
# Header layout #
################

black-favicon: "/img/white-safe.ico"

background-img: "../img/intro-bg-1.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text

- text: "Hi there, Thanks for passing by my page"
- text: "I hope you are having a good day !"

me-img: "/img/author_img_big.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "nadiametoui"

syntax-highlight: True

############
# Timeline #
############

educs:
  - image: "/img/timeline/unitn.png"
    date: "2013 - Today"
    institution: "University of Trento"
    description: "PhD. In Computer Security"
  - image: "/img/timeline/esprit.png"
    date: "2010-2013"
    institution: "Esprit University"
    description: "MSc. In Computer Engineering"
  - image: "/img/timeline/insat.png"
    date: "2006 - 2009"
    institution: "Tunis Institute of Technology"
    description: "BSc. In Computer & Telecom. Networks"

    

# First image of the Timeline

#timeline-img: "/img/timeline/author_img.png"

##################
# Pro Experience #
##################

exper:
  - image: "/img/timeline/sap_fbk.png"
    date: "September 2013 - Today"
    institution: "SAP Labs France and FBK"
    description: "Early Stage Researcher"
  - image: "/img/timeline/sap.png"
    date: "January 2010- June 2013"
    institution: "SAP Labs France"
    description: "Internship in The S&T Research Unit"
  - image: "/img/timeline/humanit.png"
    date: "September - December 2012"
    institution: "Rayan Dev for Supinfo Paris"
    description: "Freelance Wen Dev"
  - image: "/img/timeline/esprit.png"
    date: "2012"
    institution: "EspriTech: Cloud Research Unit"
    description: "Teaching Assistant"
  - image: "/img/timeline/telnet.png"
    date: "May - October 2010"
    institution: "Telnet Group"
    description: "Validation Technician"
  - image: "/img/timeline/poste.png"
    date: "September - February 2010"
    institution: "Tunisian National Posts (ONP)"
    description: "Undergrad Internship"
  - image: "/img/timeline/tunisiana.png"
    date: "June - August 2009"
    institution: "Orascom Telecom Tunisia"
    description: "Summer Internship"

    

###########
# Contact #
###########

email: "nadia.metoui@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Nadia Metoui is a PhD Student in Information Security & Privacy in the University od Trento, Italy. 
Nadia obtained the equivalent of a BSc in Computer Networks and Telecommunication (in 2010) and an Engineering degree in computer science (in 2013)."
author_blurb_image: "/img/author_img_small.png"

##################
# Social Buttons #
##################

social:
  - title: "linkedin"
    url: "https://fr.linkedin.com/in/nadia-metoui-84294952/"
  - title: "google"
    url: "https://scholar.google.fr/citations?user=_dRKB4oAAAAJ&hl=fr&oi=ao"
  - title: "envelope-o"
    url: "mailto:nadia.metoui@gmail.com"

############
# 404 page #
############

404-img: "/img/author.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About Me: 'about'
  Blog: 'latest-post'
  Education: 'education'
  Professional Exp: 'experience'
  Publications: 'publications'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "README 2.md", CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
